*** Settings ***
Documentation     Generated by _gherkin2robotframework on 2021-02-27T17:55:55.249165_
Library           Collections
Resource          ../resources/apiResources.robot
Library           requests
Library           ../lib/rest_util/RestGeneric.py

*** Keywords ***
User set POST user creation api endpoint.
    Set Global Variable    ${create_user_endpoint}    ${BASE_URL}/users

User send POST public-api/users for create user in system with access token and user information.
    ${request_header}    Create Dictionary    Content-Type=application/json    Accept=*/*    Authorization=Bearer ${ACCESS_TOKEN}
    ${content}    ${response_code}    ${header}    Execute Post Request    ${create_user_endpoint}    {"name":"${USER_NAME}", "gender":"${GENDER}", "email":"${EMAIL_ADD}", "status":"${STATUS}"}    ${request_header}
    ${content}    Load Json    ${content}
    ${content1}    Convert To Dictionary    ${content}
    ${code}    Get Value By Key From Json    ${content1}    code
    ${data}    Get Value By Key From Json    ${content1}    data
    ${data}    Convert To Dictionary    ${data}
    ${id}    Get Value By Key From Json    ${data}    id
    ${name}    Get Value By Key From Json    ${data}    name
    ${email}    Get Value By Key From Json    ${data}    email
    ${user_status}    Get Value By Key From Json    ${data}    status
    Set Global Variable    ${user_id}    ${id}
    Should Be Equal    ${name}    ${USER_NAME}
    Should Be Equal    ${email}    ${EMAIL_ADD}
    Should Be Equal    ${user_status}    ${STATUS}
    Should Be Equal As Strings    ${code}    201
    Should Be Equal As Strings    ${response_code}    200

User should be created in system with data provided.
    ${request_header}    Create Dictionary    Content-Type=application/json    Accept=*/*    Authorization=Bearer ${ACCESS_TOKEN}
    ${content}    ${response_code}    ${header}    Execute Get Request    ${create_user_endpoint}?email=${EMAIL_ADD}    ${request_header}
    ${content}    Load Json    ${content}
    ${content1}    Convert To Dictionary    ${content}
    ${code}    Get Value By Key From Json    ${content1}    code
    ${data}    Get Value By Key From Json    ${content1}    data
    ${user_id}    Convert To String    ${user_id}
    ${data}    Convert To String    ${data}
    Should Contain    ${data}    ${EMAIL_ADD}
    Should Contain    ${data}    ${STATUS}
    Should Contain    ${data}    ${USER_NAME}
    Should Contain    ${data}    ${user_id}
    Should Contain    ${data}    ${GENDER}
    Should Be Equal As Strings    ${response_code}    200
    Should Be Equal As Strings    ${code}    200

User set PUT user modification api endpoint.
    Set Global Variable    ${modify_user_endpoint}    ${BASE_URL}/users/${user_id}

User send PUT public-api/users for modify user in system with access token and user information.
    ${request_header}    Create Dictionary    Content-Type=application/json    Accept=*/*    Authorization=Bearer ${ACCESS_TOKEN}
    ${content}    ${response_code}    ${header}    Execute Put Request    ${modify_user_endpoint}    {"name":"${NEW_USER_NAME}", "gender":"${GENDER}", "email":"${EMAIL_ADD}", "status":"${STATUS}"}    ${request_header}
    ${content}    Load Json    ${content}
    ${content1}    Convert To Dictionary    ${content}
    ${code}    Get Value By Key From Json    ${content1}    code
    ${data}    Get Value By Key From Json    ${content1}    data
    ${data}    Convert To Dictionary    ${data}
    ${id}    Get Value By Key From Json    ${data}    id
    ${name}    Get Value By Key From Json    ${data}    name
    ${email}    Get Value By Key From Json    ${data}    email
    ${user_status}    Get Value By Key From Json    ${data}    status
    Should Be Equal    ${name}    ${NEW_USER_NAME}
    Should Be Equal    ${email}    ${EMAIL_ADD}
    Should Be Equal    ${user_status}    ${STATUS}
    Should Be Equal    ${user_id}    ${id}
    Should Be Equal As Strings    ${code}    200
    Should Be Equal As Strings    ${response_code}    200

User should be renamed in the system with data provided.
    ${request_header}    Create Dictionary    Content-Type=application/json    Accept=*/*    Authorization=Bearer ${ACCESS_TOKEN}
    ${content}    ${response_code}    ${header}    Execute Get Request    ${create_user_endpoint}?email=${EMAIL_ADD}    ${request_header}
    ${content}    Load Json    ${content}
    ${content1}    Convert To Dictionary    ${content}
    ${code}    Get Value By Key From Json    ${content1}    code
    ${data}    Get Value By Key From Json    ${content1}    data
    ${user_id}    Convert To String    ${user_id}
    ${data}    Convert To String    ${data}
    Should Contain    ${data}    ${EMAIL_ADD}
    Should Contain    ${data}    ${STATUS}
    Should Contain    ${data}    ${NEW_USER_NAME}
    Should Contain    ${data}    ${user_id}
    Should Contain    ${data}    ${GENDER}
    Should Be Equal As Strings    ${code}    200
    Should Be Equal As Strings    ${response_code}    200

User set POST posts and comment for particular user api endpoint.
    Set Global Variable    ${create_posts_endpoint}    ${BASE_URL}/users/${user_id}/posts

User send POST /public-api/users/userid/posts and /public-api/posts/postid/comments for create post and comment for particular user in system with access token and user information.
    ${request_header}    Create Dictionary    Content-Type=application/json    Accept=*/*    Authorization=Bearer ${ACCESS_TOKEN}
    ${content}    ${response_code}    ${header}    Execute Post Request    ${create_posts_endpoint}    {"title":"${POSTS_TITLE}","body":"${BODY_POSTS}"}    ${request_header}
    ${content}    Load Json    ${content}
    ${content1}    Convert To Dictionary    ${content}
    ${code}    Get Value By Key From Json    ${content1}    code
    ${data}    Get Value By Key From Json    ${content1}    data
    ${data}    Convert To Dictionary    ${data}
    ${id}    Get Value By Key From Json    ${data}    id
    ${userid}    Get Value By Key From Json    ${data}    user_id
    ${posts_title_actual}    Get Value By Key From Json    ${data}    title
    ${posts_body_actual}    Get Value By Key From Json    ${data}    body
    Set Global Variable    ${posts_id}    ${id}
    Should Be Equal    ${user_id}    ${userid}
    Should Be Equal    ${posts_title_actual}    ${POSTS_TITLE}
    Should Be Equal    ${posts_body_actual}    ${BODY_POSTS}
    Should Be Equal As Strings    ${code}    201
    Should Be Equal As Strings    ${response_code}    200
    Set Global Variable    ${create_comment_posts_endpoint}    ${BASE_URL}/posts/${posts_id}/comments
    ${content}    ${response_code}    ${header}    Execute Post Request    ${create_comment_posts_endpoint}    { "name": "${USER_NAME}","email": "${EMAIL_ADD}","body": "${BODY_COMMENTS}"}    ${request_header}
    ${content}    Load Json    ${content}
    ${content1}    Convert To Dictionary    ${content}
    ${code}    Get Value By Key From Json    ${content1}    code
    ${data}    Get Value By Key From Json    ${content1}    data
    ${data}    Convert To Dictionary    ${data}
    ${id}    Get Value By Key From Json    ${data}    id
    ${name}    Get Value By Key From Json    ${data}    name
    ${email}    Get Value By Key From Json    ${data}    email
    ${comment_body}    Get Value By Key From Json    ${data}    body
    ${postsid}    Get Value By Key From Json    ${data}    post_id
    Set Global Variable    ${comment_id}    ${id}
    Should Be Equal    ${name}    ${USER_NAME}
    Should Be Equal    ${email}    ${EMAIL_ADD}
    Should Be Equal    ${comment_body}    ${BODY_COMMENTS}
    Should Be Equal    ${postsid}    ${posts_id}
    Should Be Equal As Strings    ${code}    201
    Should Be Equal As Strings    ${response_code}    200

posts and comment should be created for user with given data in system.
    ${request_header}    Create Dictionary    Content-Type=application/json    Accept=*/*    Authorization=Bearer ${ACCESS_TOKEN}
    ${content}    ${response_code}    ${header}    Execute Get Request    ${create_comment_posts_endpoint}    ${request_header}
    ${content}    Load Json    ${content}
    ${content1}    Convert To Dictionary    ${content}
    ${code}    Get Value By Key From Json    ${content1}    code
    ${data}    Get Value By Key From Json    ${content1}    data
    ${data_length}    Get Length    ${data}
    FOR    ${item}    IN RANGE    ${data_length}
    ${data}    Get From List    ${data}    ${item}
    ${data}    Convert To Dictionary    ${data}
    ${id}    Get Value By Key From Json    ${data}    id
    ${postsid}    Get Value By Key From Json    ${data}    post_id
    ${name}    Get Value By Key From Json    ${data}    name
    ${email}    Get Value By Key From Json    ${data}    email
    ${comment_body}    Get Value By Key From Json    ${data}    body
    Should Be Equal    ${name}    ${USER_NAME}
    Should Be Equal    ${email}    ${EMAIL_ADD}
    Should Be Equal    ${comment_body}    ${BODY_COMMENTS}
    Should Be Equal    ${postsid}    ${posts_id}
    Should Be Equal    ${id}    ${comment_id}
    Should Be Equal As Strings    ${code}    200
    Should Be Equal As Strings    ${response_code}    200
    END

User set DELETE user api endpoint.
    Set Global Variable    ${delete_user_endpoint}    ${BASE_URL}/users/${user_id}

User send DELETE public-api/users/userid to delete user from system with access token.
    ${request_header}    Create Dictionary    Content-Type=application/json    Accept=*/*    Authorization=Bearer ${ACCESS_TOKEN}
    ${content}    ${response_code}    ${header}    Execute Delete Request    ${delete_user_endpoint}    ${request_header}
    ${content}    Load Json    ${content}
    ${content1}    Convert To Dictionary    ${content}
    ${code}    Get Value By Key From Json    ${content1}    code
    ${data}    Get Value By Key From Json    ${content1}    data
    ${data}    Convert To String    ${data}
    Should Be Equal    ${data}    None
    Should Be Equal As Strings    ${code}    204
    Should Be Equal As Strings    ${response_code}    200

User should be deleted from system with all data.
    ${request_header}    Create Dictionary    Content-Type=application/json    Accept=*/*    Authorization=Bearer ${ACCESS_TOKEN}
    ${content}    ${response_code}    ${header}    Execute Get Request    ${create_user_endpoint}?email=${EMAIL_ADD}    ${request_header}
    ${content}    Load Json    ${content}
    ${content1}    Convert To Dictionary    ${content}
    ${data}    Get Value By Key From Json    ${content1}    data
    Should Be Empty    ${data}
    Should Be Equal As Strings    ${response_code}    200
    ${content}    ${response_code}    ${header}    Execute Get Request    ${create_comment_posts_endpoint}    ${request_header}
    ${content}    Load Json    ${content}
    ${content1}    Convert To Dictionary    ${content}
    ${data}    Get Value By Key From Json    ${content1}    data
    Should Be Empty    ${data}
    Should Be Equal As Strings    ${response_code}    200
